# Generated by Django 5.2.5 on 2025-08-25 00:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'user'), ('assistant', 'assistant')], max_length=10)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trace', models.JSONField(blank=True, null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='agent.conversation')),
            ],
        ),
        migrations.CreateModel(
            name='ToolRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_id', models.CharField(max_length=40)),
                ('tool_name', models.CharField(max_length=32)),
                ('input_text', models.TextField()),
                ('output_text', models.TextField()),
                ('meta', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_runs', to='agent.conversation')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agent.message')),
            ],
        ),
        migrations.CreateModel(
            name='MemoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('scope', models.CharField(choices=[('thread', 'thread'), ('user', 'user'), ('session', 'session')], default='thread', max_length=10)),
                ('namespace', models.CharField(db_index=True, max_length=48)),
                ('key', models.CharField(db_index=True, max_length=120)),
                ('data_type', models.CharField(choices=[('number', 'number'), ('text', 'text'), ('json', 'json')], default='text', max_length=8)),
                ('value_text', models.TextField(blank=True, default='')),
                ('number_value', models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True)),
                ('value_json', models.JSONField(blank=True, null=True)),
                ('is_persistent', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agent.conversation')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('source_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agent.message')),
            ],
            options={
                'indexes': [models.Index(fields=['namespace', 'key'], name='agent_memor_namespa_10fd1a_idx'), models.Index(fields=['scope', 'namespace', 'key'], name='agent_memor_scope_00d62c_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user', 'scope', 'namespace', 'key'), name='uniq_user_mem_per_key'), models.UniqueConstraint(condition=models.Q(('session_key__isnull', False), ('user__isnull', True)), fields=('session_key', 'scope', 'namespace', 'key'), name='uniq_session_mem_per_key'), models.UniqueConstraint(condition=models.Q(('conversation__isnull', False)), fields=('conversation', 'scope', 'namespace', 'key'), name='uniq_thread_mem_per_key')],
            },
        ),
    ]
